import { useState, useEffect } from 'react';
import { Cloud, Sun, CloudRain, CloudLightning, Snowflake, Loader } from 'lucide-react';

interface WeatherProps {
    date: string;
    lat?: number;
    lng?: number;
    placeName?: string;
    fallbackCity?: string;
    mapLink?: string;
}

const geoCache: Record<string, {lat: number, lng: number}> = {};
const weatherCache: Record<string, any> = {};

export function WeatherWidget({ date, lat, lng, placeName, fallbackCity, mapLink }: WeatherProps) {
    const [weather, setWeather] = useState<{ min: number, max: number, code: number, isForecast: boolean } | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (!date) {
            setLoading(false);
            return;
        }

        const fetchWeather = async () => {
            try {
                // Ensure the date is strictly YYYY-MM-DD to avoid 400 errors from Open-Meteo
                let formattedDate = date.split('T')[0].split(' ')[0];
                
                // Convert DD-MM-YYYY or DD-MM-YY to YYYY-MM-DD
                const parts = formattedDate.split(/[-/]/);
                if (parts.length === 3 && parts[0].length <= 2) {
                    let [d, m, y] = parts;
                    if (y.length === 2) y = "20" + y; // Assume 2000s for YY
                    
                    // Basic sanity check, e.g. 18-04-2025 -> 2025-04-18
                    if (y.length === 4) {
                        // Pad single digits
                        if (d.length === 1) d = "0" + d;
                        if (m.length === 1) m = "0" + m;
                        formattedDate = `${y}-${m}-${d}`;
                    }
                }
                
                let currentLat = lat;
                let currentLng = lng;

                // 1. Try to extract coordinates from a Google Maps link if lat/lng are missing
                if ((!currentLat || !currentLng) && mapLink) {
                    // @lat,lng  (pin / directions URLs)
                    const atMatch = mapLink.match(/@(-?\d+\.\d+),(-?\d+\.\d+)/);
                    // ?query=lat,lng  (generated by activity search: maps/search/?api=1&query=22.30,70.80)
                    const queryMatch = mapLink.match(/[?&]query=(-?\d+\.\d+),(-?\d+\.\d+)/);
                    // ?q=lat,lng
                    const qMatch = mapLink.match(/[?&]q=(-?\d+\.\d+),(-?\d+\.\d+)/);
                    // !3dlat!4dlng  (embedded/place URLs)
                    const pb3d = mapLink.match(/!3d(-?\d+\.\d+)!4d(-?\d+\.\d+)/);

                    const m = atMatch || queryMatch || qMatch || pb3d;
                    if (m) {
                        currentLat = parseFloat(m[1]);
                        currentLng = parseFloat(m[2]);
                    }
                }

                // 2. If mapLink is plain text (city name typed without selecting from dropdown), geocode it
                if ((!currentLat || !currentLng) && mapLink && !mapLink.startsWith('http')) {
                    const cacheKeyText = `text:${mapLink}`;
                    if (geoCache[cacheKeyText]) {
                        currentLat = geoCache[cacheKeyText].lat;
                        currentLng = geoCache[cacheKeyText].lng;
                    } else {
                        try {
                            const geoRes = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(mapLink)}&count=1&language=en&format=json`);
                            if (geoRes.ok) {
                                const geoData = await geoRes.json();
                                if (geoData.results?.length > 0) {
                                    const geoLat: number = geoData.results[0].latitude;
                                    const geoLng: number = geoData.results[0].longitude;
                                    currentLat = geoLat;
                                    currentLng = geoLng;
                                    geoCache[cacheKeyText] = { lat: geoLat, lng: geoLng };
                                }
                            }
                        } catch(e) { /* ignore */ }
                    }
                }

                // 3. Geocode fallback using the trip's overall destination city
                if (!currentLat || !currentLng) {
                    if (fallbackCity) {
                        if (geoCache[fallbackCity]) {
                            currentLat = geoCache[fallbackCity].lat;
                            currentLng = geoCache[fallbackCity].lng;
                        } else {
                            try {
                                const geoRes = await fetch(`https://geocoding-api.open-meteo.com/v1/search?name=${encodeURIComponent(fallbackCity)}&count=1&language=en&format=json`);
                                if (geoRes.ok) {
                                    const geoData = await geoRes.json();
                                    if (geoData.results && geoData.results.length > 0) {
                                        const geoLat: number = geoData.results[0].latitude;
                                        const geoLng: number = geoData.results[0].longitude;
                                        currentLat = geoLat;
                                        currentLng = geoLng;
                                        geoCache[fallbackCity] = { lat: geoLat, lng: geoLng };
                                    }
                                }
                            } catch(e) { /* ignore geocode failure */ }
                        }
                    }
                }

                if (!currentLat || !currentLng) {
                    setLoading(false);
                    return;
                }

                const cacheKey = `${currentLat},${currentLng},${formattedDate}`;
                if (weatherCache[cacheKey]) {
                    setWeather(weatherCache[cacheKey]);
                    setLoading(false);
                    return;
                }

                // Try forecast API first (supports up to 14-16 days in advance + past dates)
                let res = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${currentLat}&longitude=${currentLng}&daily=weather_code,temperature_2m_max,temperature_2m_min&start_date=${formattedDate}&end_date=${formattedDate}&timezone=auto`);
                
                let isForecast = true;

                // If date is too far in the future, fallback to last year's historical data
                if (!res.ok) {
                   const lastYearDate = new Date(formattedDate);
                   lastYearDate.setFullYear(lastYearDate.getFullYear() - 1);
                   const formattedOldDate = lastYearDate.toISOString().split('T')[0];

                   res = await fetch(`https://archive-api.open-meteo.com/v1/archive?latitude=${currentLat}&longitude=${currentLng}&daily=weather_code,temperature_2m_max,temperature_2m_min&start_date=${formattedOldDate}&end_date=${formattedOldDate}&timezone=auto`);
                   isForecast = false;
                }

                if (!res.ok) {
                    setLoading(false);
                    return;
                }

                const data = await res.json();
                if (data.daily && data.daily.temperature_2m_max?.length > 0) {
                    const finalWeather = {
                        max: data.daily.temperature_2m_max[0],
                        min: data.daily.temperature_2m_min[0],
                        code: data.daily.weather_code[0],
                        isForecast
                    };
                    weatherCache[cacheKey] = finalWeather;
                    setWeather(finalWeather);
                }
                setLoading(false);
            } catch (err) {
                setLoading(false);
            }
        };

        fetchWeather();
    }, [date, lat, lng, placeName, fallbackCity]);

    if (loading) return <div style={{ display: 'inline-flex', alignItems: 'center', gap: '4px', fontSize: '11px', color: 'var(--text-light)' }}><Loader size={12} className="animate-spin"/> Loading weather...</div>;
    if (!weather) return null;

    // Map WMO codes to icons
    const getIcon = (code: number) => {
        if (code === 0) return <Sun size={14} color="#FDB813" />; // Clear
        if (code <= 3) return <Cloud size={14} color="#FDB813" />; // Partly Cloudy
        if (code >= 45 && code <= 48) return <Cloud size={14} color="#9ca3af" />; // Fog
        if (code >= 51 && code <= 67) return <CloudRain size={14} color="#60a5fa" />; // Drizzle/Rain
        if (code >= 71 && code <= 77) return <Snowflake size={14} color="#93c5fd" />; // Snow
        if (code >= 80 && code <= 82) return <CloudRain size={14} color="#3b82f6" />; // Showers
        if (code >= 95) return <CloudLightning size={14} color="#eab308" />; // Thunderstorm
        return <Cloud size={14} />;
    };

    const getConditionString = (code: number) => {
        if (code === 0) return 'Clear';
        if (code <= 3) return 'Partly Cloudy';
        if (code >= 45 && code <= 48) return 'Foggy';
        if (code >= 51 && code <= 67) return 'Rainy';
        if (code >= 71 && code <= 77) return 'Snow';
        if (code >= 80 && code <= 82) return 'Showers';
        if (code >= 95) return 'Storms';
        return 'Cloudy';
    };

    return (
        <div style={{ display: 'inline-flex', alignItems: 'center', gap: '6px', background: 'rgba(255,255,255,0.05)', padding: '4px 8px', borderRadius: '16px', fontSize: '12px', border: '1px solid rgba(255,255,255,0.1)' }} title={weather.isForecast ? "Forecasted weather for this date" : "Typical weather based on historical data for this time of year"}>
            {getIcon(weather.code)}
            <span style={{ fontWeight: 600, color: 'white' }}>{Math.round(weather.max)}°C</span>
            <span style={{ color: 'var(--text-light)' }}>/ {Math.round(weather.min)}°C</span>
            <span style={{ marginLeft: '4px', color: 'var(--primary)', fontSize: '10px', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{getConditionString(weather.code)}</span>
            {!weather.isForecast && <span style={{ opacity: 0.5, fontSize: '10px', marginLeft: '-2px' }}>(AVG)</span>}
        </div>
    );
}
